package triegun

import (
	"fmt"
	"io"
	"text/template"
)

func GenerateHasPrefix(w io.Writer, tag_name string, signatures []string) error {
	if len(signatures) < 1 {
		return fmt.Errorf("GenerateHasPrefix requires at least one string to make trie tree")
	}
	if tag_name != "" && !reId.MatchString(tag_name) {
		return fmt.Errorf(`GenerateHasPrefix: tag name must be an identifier, but "%s" is not`, tag_name)
	}
	st := newDFAFromStrings(signatures)
	return templPrefix.Execute(w, map[string]interface{}{
		"TagName": tag_name,
		"States":  allStatesUpToGoal(st),
	})
}

var templPrefix = template.Must(template.New("prefix").Parse(`
// DO NOT EDIT!
// Code generated by go-triegun <https://github.com/Maki-Daisuke/go-triegun>
// DO NOT EDIT!

import "unsafe"

func HasPrefix{{.TagName}}String(str string) bool {
  return HasPrefix{{.TagName}}(*(*[]byte)(unsafe.Pointer(&str)))
}

func HasPrefix{{.TagName}}(bytes []byte) bool {
  defer func(){
    recover() // Must be "index out of range" error for string.
              // Ignore and return false.
  }()

  i := 0
  goto STATE_{{ with index .States 0 }}{{ print .Id }}{{ end }}

{{ range .States }}
  STATE_{{ .Id }}:
  {{ if .IsGoal }}
      return true
  {{ else }}
    switch bytes[i] {
    {{ range $key, $next := .Nexts }}
    case {{ printf "%q" $key }}:
      i++
      goto STATE_{{ $next.Id }}
    {{ end }}
    default:
      return false
    }
  {{ end }}
{{ end }}
}
`))
